name: Upload Assets

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to build from
        required: true

jobs:
  upload-deb-package:
    runs-on: ubuntu-latest

    steps:
      - name: Determine ref
        id: ref
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "ref=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
            ref="${{ github.event.inputs.tag }}"
          else
            echo "ref=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
            ref="${{ github.event.release.tag_name }}"
          fi
          echo "Determined ref: ${{ steps.ref.outputs.ref }}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.ref }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -yq debcrafter-0 tea-pkg-0

      - name: Build DEB package
        run: |
          debcrafter run --container-exec docker

      - name: Upload DEB package
        env:
          GITEA_BASE_URL: https://git.0xmax42.io
          GITEA_TOKEN: ${{ secrets.RELEASE_PUBLISH_TOKEN }}
        run: |
          tea-pkg publish-deb debrepo ./dist/*.deb -o
