# .github/workflows/build.yml
name: Build-Deb

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Debian package
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Sparse checkout of debrepo (only scboot/)
        run: |
          git init debrepo
          cd debrepo
          git remote add origin https://${{ secrets.DEBREPO_USERNAME }}:${{ secrets.DEBREPO_TOKEN }}@git.0xmax42.io/maxp/debrepo.git
          git config core.sparseCheckout true
          echo "scboot/" >> .git/info/sparse-checkout
          git pull --depth=1 origin packages
          git checkout -b packages

      - name: Copy .deb to debrepo scboot directory
        run: |
          mkdir -p debrepo/scboot
          cp ./dist/scboot_*.deb debrepo/scboot/

      - name: Commit and push .deb package to debrepo
        working-directory: debrepo
        run: |
          set -euo pipefail
          git config user.name "$CI_COMMIT_AUTHOR_NAME"
          git config user.email "$CI_COMMIT_AUTHOR_EMAIL"

          # Nur adden, wenn Datei nicht bereits im Git-Index
          for file in scboot/scboot_*.deb; do
            if [ -e "$file" ]; then
              if git ls-files --error-unmatch "$file" > /dev/null 2>&1; then
                echo "Datei $file ist bereits im Repository – überspringe."
              else
                echo "Neue Datei $file wird hinzugefügt."
                git add "$file"
              fi
            fi
          done

          git commit -m "Add scboot package version ${{ steps.read_version.outputs.VERSION }}" || echo "No changes to commit"
          git push origin packages
